// <auto-generated />
using System;
using APIServer.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIServer.Persistence.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20211123134650_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("APIServer.Domain.Core.Models.Events.DomainEvent", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActorID")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("APIServer.Domain.Core.Models.WebHooks.WebHook", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("HookEvents")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastTrigger")
                        .HasColumnType("TEXT");

                    b.Property<string>("Secret")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebHookUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("WebHooks");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            ContentType = "application/json",
                            HookEvents = "hook",
                            IsActive = true,
                            WebHookUrl = "https://localhost:5015/hookloopback"
                        },
                        new
                        {
                            ID = 2L,
                            ContentType = "application/json",
                            HookEvents = "hook",
                            IsActive = false,
                            WebHookUrl = "https://localhost:5015/hookloopback2"
                        });
                });

            modelBuilder.Entity("APIServer.Domain.Core.Models.WebHooks.WebHookHeader", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.Property<long>("WebHookID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("WebHookID");

                    b.ToTable("WebHookHeader");
                });

            modelBuilder.Entity("APIServer.Domain.Core.Models.WebHooks.WebHookRecord", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<string>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<int>("HookType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("TEXT");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("WebHookID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("WebHookID");

                    b.ToTable("WebHooksHistory");
                });

            modelBuilder.Entity("APIServer.Domain.Core.Models.Events.WebHookCreated", b =>
                {
                    b.HasBaseType("APIServer.Domain.Core.Models.Events.DomainEvent");

                    b.Property<long>("WebHookId")
                        .HasColumnType("INTEGER");

                    b.ToTable("WebHookCreatedEvent");
                });

            modelBuilder.Entity("APIServer.Domain.Core.Models.Events.WebHookRemoved", b =>
                {
                    b.HasBaseType("APIServer.Domain.Core.Models.Events.DomainEvent");

                    b.Property<long>("WebHookId")
                        .HasColumnType("INTEGER");

                    b.ToTable("WebHookRemovedEvent");
                });

            modelBuilder.Entity("APIServer.Domain.Core.Models.Events.WebHookUpdated", b =>
                {
                    b.HasBaseType("APIServer.Domain.Core.Models.Events.DomainEvent");

                    b.Property<long>("WebHookId")
                        .HasColumnType("INTEGER");

                    b.ToTable("WebHookUpdatedEvent");
                });

            modelBuilder.Entity("APIServer.Domain.Core.Models.WebHooks.WebHookHeader", b =>
                {
                    b.HasOne("APIServer.Domain.Core.Models.WebHooks.WebHook", "WebHook")
                        .WithMany("Headers")
                        .HasForeignKey("WebHookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebHook");
                });

            modelBuilder.Entity("APIServer.Domain.Core.Models.WebHooks.WebHookRecord", b =>
                {
                    b.HasOne("APIServer.Domain.Core.Models.WebHooks.WebHook", "WebHook")
                        .WithMany("Records")
                        .HasForeignKey("WebHookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebHook");
                });

            modelBuilder.Entity("APIServer.Domain.Core.Models.Events.WebHookCreated", b =>
                {
                    b.HasOne("APIServer.Domain.Core.Models.Events.DomainEvent", null)
                        .WithOne()
                        .HasForeignKey("APIServer.Domain.Core.Models.Events.WebHookCreated", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APIServer.Domain.Core.Models.Events.WebHookRemoved", b =>
                {
                    b.HasOne("APIServer.Domain.Core.Models.Events.DomainEvent", null)
                        .WithOne()
                        .HasForeignKey("APIServer.Domain.Core.Models.Events.WebHookRemoved", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APIServer.Domain.Core.Models.Events.WebHookUpdated", b =>
                {
                    b.HasOne("APIServer.Domain.Core.Models.Events.DomainEvent", null)
                        .WithOne()
                        .HasForeignKey("APIServer.Domain.Core.Models.Events.WebHookUpdated", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APIServer.Domain.Core.Models.WebHooks.WebHook", b =>
                {
                    b.Navigation("Headers");

                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
